// <auto-generated />
namespace LADOT_Web_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class destinationforhistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(destinationforhistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201704261734316_destination-for-history"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
